### ISSUE TITLE
arm架构下挂载115查看宿主机挂载目录没有网盘文件

### ISSUE THREAD

**Issue by zhuweitung** [cloud-fs/cloud-fs.github.io#157]
运行环境：
+ ubuntu 22.04.3 LTS
+ Docker version 20.10.12, build e91ed57
+ Docker Compose version v2.2.3
+ cloudnas/clouddrive2:0.7.16

![image](https://github.com/user-attachments/assets/b0b14b57-241a-4e40-b794-ffab3152e121)

docker-compose.yml:
```yml
version: "2.1"
services:
  cloudnas:
    image: cloudnas/clouddrive2:latest
    container_name: clouddrive2
    environment:
      - TZ=Asia/Shanghai
      - CLOUDDRIVE_HOME=/Config
    volumes:
      - /CloudNAS:/CloudNAS:shared
      - ./config:/Config
    devices:
      - /dev/fuse:/dev/fuse
    restart: unless-stopped
    pid: "host"
    privileged: true
    cap_add:
      - SYS_ADMIN
    ports:
      - 19798:19798
```

现象：
挂载115权限设置为777，clouddrive2网页上能看到网盘内的内容
![image](https://github.com/user-attachments/assets/9492d33e-43fc-4dea-938d-2d25b3af2608)

但在宿主机文件中查看权限还是755，进入目录也看不到网盘的目录及内容
![image](https://github.com/user-attachments/assets/ebe7f9a9-bbfa-4e37-866a-2fb3fce28a79)

同样的操作在x86的服务器上执行，能够正常访问挂载目录下网盘的目录及内容
